<script lang="ts">
  import reportData from './lib/report-data.json'
  import { type Report, SEVERITY_COLOR, statusColor } from './lib/report'
  import StackedTimeSeries from './lib/StackedTimeSeries.svelte'
  import Sparkline from './lib/Sparkline.svelte'

  const report = reportData as Report

  function fmtTime(t: string): string {
    return new Date(t).toISOString().replace('T', ' ').replace('.000Z', 'Z').replace('Z', ' UTC')
  }
  function shortId(id: string): string {
    return id.slice(0, 12)
  }
  const totalSeverity = report.logSeverity.reduce((a, s) => a + s.count, 0) || 1

  const tiles = [
    { label: 'Logs', value: report.summary.logs },
    { label: 'Errors', value: report.summary.errorLogs, warn: report.summary.errorLogs > 0 },
    { label: 'Spans', value: report.summary.spans },
    { label: 'Traces', value: report.summary.traces },
    { label: 'Metric points', value: report.summary.metricPoints },
  ]
</script>

<main>
  <header>
    <div class="brand">
      <span class="logo">◇</span>
      <div>
        <h1>otelhouseui report</h1>
        <p class="sub">
          OpenTelemetry logs · metrics · traces from ClickHouse —
          <a href={report.source.runURL}>{report.source.repo}@{shortId(report.source.commit)}</a>
        </p>
      </div>
    </div>
    <div class="meta">
      <div>generated <b>{fmtTime(report.generatedAt)}</b></div>
      <div>window {fmtTime(report.window.from)} → {fmtTime(report.window.to)}</div>
    </div>
  </header>

  <section class="tiles">
    {#each tiles as tile (tile.label)}
      <div class="tile" class:warn={tile.warn}>
        <div class="tile-value">{tile.value.toLocaleString('en-US')}</div>
        <div class="tile-label">{tile.label}</div>
      </div>
    {/each}
  </section>

  <section class="card">
    <div class="card-head">
      <h2>Log volume over time</h2>
      <div class="legend">
        {#each report.logSeverity as s (s.severity)}
          <span class="chip"><i style="background:{SEVERITY_COLOR[s.severity] ?? '#8b8d98'}"></i>{s.severity}</span>
        {/each}
      </div>
    </div>
    {#if report.logVolume.length}
      <StackedTimeSeries data={report.logVolume} />
    {:else}
      <p class="empty">No log volume data in this window.</p>
    {/if}
  </section>

  <section class="grid2">
    <div class="card">
      <div class="card-head"><h2>Log severity</h2></div>
      <div class="sev-bars">
        {#each report.logSeverity as s (s.severity)}
          <div class="sev-row">
            <span class="sev-name">{s.severity}</span>
            <div class="sev-track">
              <div class="sev-fill" style="width:{(s.count / totalSeverity) * 100}%;background:{SEVERITY_COLOR[s.severity] ?? '#8b8d98'}"></div>
            </div>
            <span class="sev-count">{s.count.toLocaleString('en-US')}</span>
          </div>
        {/each}
      </div>
    </div>

    <div class="card">
      <div class="card-head"><h2>Metrics</h2></div>
      {#if report.metrics.length}
        {#each report.metrics as m (m.name)}
          <div class="metric">
            <div class="metric-head">
              <code>{m.name}</code>
              <span class="metric-latest">{m.latest}<small>{m.unit && m.unit !== '1' ? ' ' + m.unit : ''}</small></span>
            </div>
            <Sparkline points={m.points} height={110} />
          </div>
        {/each}
      {:else}
        <p class="empty">No metric samples in this window.</p>
      {/if}
    </div>
  </section>

  <section class="card">
    <div class="card-head"><h2>Recent traces</h2></div>
    {#if report.traces.length}
      <div class="table-wrap">
        <table>
          <thead>
            <tr><th>Trace</th><th>Service</th><th>Root span</th><th class="num">Spans</th><th class="num">Duration</th><th>Status</th><th>Start</th></tr>
          </thead>
          <tbody>
            {#each report.traces as t (t.traceId)}
              <tr>
                <td><code>{shortId(t.traceId)}</code></td>
                <td>{t.service}</td>
                <td>{t.rootSpan}</td>
                <td class="num">{t.spanCount}</td>
                <td class="num">{t.durationMs.toFixed(1)} ms</td>
                <td><span class="status" style="color:{statusColor(t.status)}">●</span> {t.status.replace('STATUS_CODE_', '')}</td>
                <td class="muted">{fmtTime(t.startTime)}</td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {:else}
      <p class="empty">No traces in this window.</p>
    {/if}
  </section>

  <footer>
    Generated by <a href="https://github.com/guettli/otelhouseui">otelhouseui</a> ·
    static report, no live queries · one self-contained HTML file.
  </footer>
</main>

<style>
  :global(:root) {
    --bg: #f6f7f9;
    --card: #ffffff;
    --fg: #1a1d24;
    --muted: #6b7280;
    --border: #e4e6eb;
    --grid: #edeff2;
    --accent: #3e63dd;
  }
  @media (prefers-color-scheme: dark) {
    :global(:root) {
      --bg: #0e1116;
      --card: #171b22;
      --fg: #e6e8ec;
      --muted: #8b94a3;
      --border: #262b34;
      --grid: #222831;
      --accent: #6b8afd;
    }
  }
  :global(body) {
    margin: 0;
    background: var(--bg);
    color: var(--fg);
    font: 14px/1.5 -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
  }
  main { max-width: 900px; margin: 0 auto; padding: 28px 20px 60px; }
  header { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; }
  .brand { display: flex; gap: 12px; align-items: center; }
  .logo { font-size: 28px; color: var(--accent); }
  h1 { font-size: 20px; margin: 0; }
  .sub { margin: 2px 0 0; color: var(--muted); font-size: 13px; }
  .sub a, footer a, header a { color: var(--accent); text-decoration: none; }
  .meta { text-align: right; color: var(--muted); font-size: 12px; }
  .meta b { color: var(--fg); font-weight: 600; }

  .tiles { display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin-bottom: 20px; }
  .tile { background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 16px; }
  .tile-value { font-size: 26px; font-weight: 700; letter-spacing: -0.02em; }
  .tile-label { color: var(--muted); font-size: 12px; margin-top: 2px; }
  .tile.warn .tile-value { color: #e5484d; }

  .card { background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 18px 18px 12px; margin-bottom: 20px; }
  .card-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; flex-wrap: wrap; gap: 8px; }
  h2 { font-size: 14px; margin: 0; font-weight: 600; }
  .grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }

  .legend { display: flex; gap: 12px; flex-wrap: wrap; }
  .chip { display: inline-flex; align-items: center; gap: 6px; font-size: 12px; color: var(--muted); }
  .chip i { width: 10px; height: 10px; border-radius: 3px; display: inline-block; }

  .sev-bars { display: flex; flex-direction: column; gap: 10px; padding: 6px 0; }
  .sev-row { display: grid; grid-template-columns: 56px 1fr 56px; align-items: center; gap: 10px; }
  .sev-name { font-size: 12px; color: var(--muted); }
  .sev-track { background: var(--grid); border-radius: 6px; height: 10px; overflow: hidden; }
  .sev-fill { height: 100%; border-radius: 6px; }
  .sev-count { text-align: right; font-variant-numeric: tabular-nums; }

  .metric-head { display: flex; justify-content: space-between; align-items: baseline; }
  .metric-head code { font-size: 12px; color: var(--muted); }
  .metric-latest { font-size: 20px; font-weight: 700; }
  .metric-latest small { font-size: 12px; color: var(--muted); font-weight: 400; }

  .table-wrap { overflow-x: auto; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; color: var(--muted); font-weight: 500; font-size: 12px; padding: 6px 10px; border-bottom: 1px solid var(--border); }
  td { padding: 8px 10px; border-bottom: 1px solid var(--grid); }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .muted { color: var(--muted); }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  .status { font-size: 10px; }

  .empty { color: var(--muted); padding: 16px 4px; }
  footer { color: var(--muted); font-size: 12px; text-align: center; margin-top: 12px; }

  @media (max-width: 680px) {
    .tiles { grid-template-columns: repeat(2, 1fr); }
    .grid2 { grid-template-columns: 1fr; }
    .meta { text-align: left; }
  }
</style>
